services:
  postgres:
    image: "postgres:13"
    ports:
      - "0.0.0.0:5432:5432"
    env_file: .env
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    restart: always
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgAdmin
    restart: always
    env_file: .env
    ports:
      - "0.0.0.0:9101:80"
    links:
      - "postgres:pgadmin"
    volumes:
     - "./pgadmin_data:/var/lib/pgadmin"