services:
  postgres:
    image: "postgres:13"
    ports:
      - "0.0.0.0:5432:5432"
    env_file: .env
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    restart: always
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgAdmin
    restart: always
    env_file: .env
    ports:
      - "0.0.0.0:9101:80"
    links:
      - "postgres:pgadmin"
    volumes:
     - "./pgadmin_data:/var/lib/pgadmin"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - ./redis_data:/data
  redis-insight:
    image: redis/redisinsight
    container_name: redis_insight
    ports:
      - "0.0.0.0:5540:5540"
    links:
      - "redis:redis-insight"
    volumes:
      - ./redis_insight_data:/data
    depends_on:
      - redis